### ISSUE TITLE
[GGSoC'23] Adding hamburger icon for phones 

### ISSUE THREAD

**Issue by VC6378** [akshitagupta15june/Moksh#243] opened 2023-05-21 11:00 UTC
Hey,
I would like to improve the navbar, using the hamburger icon.
Thanks and regards,
Vibhuti Chandrakar

**Comment by PR1YAM9** [comment] 2023-05-21 11:53
hello,
I would like to work on this issue, I can improve the NAVBAR by making it 100% responsive and as seen on the website there is OVERFLOW when in the lower width size(shrunk web-page). Please assign me this issue under GGSOC 23' 
Regards Priyam Maini

**Comment by rishitachail** [comment] 2023-05-21 12:30
Hello @akshitagupta15june 

Issue: Improve Responsiveness and Overflow Issue in NAVBAR

Description:
The current NAVBAR on the website lacks responsiveness, causing overflow and layout issues when viewed on smaller screen sizes. As a GGSOC '23 contributor, I propose to enhance the NAVBAR's responsiveness and resolve the overflow problem to ensure optimal user experience across different devices.

Proposed Solution:
To address this issue effectively, I suggest the following steps:

Analyze the existing NAVBAR code and identify the areas that contribute to the lack of responsiveness and the overflow problem.

Implement responsive design techniques, such as media queries, to adjust the NAVBAR's layout and content based on different screen sizes.

Test the modified NAVBAR thoroughly on various devices, including mobile, tablet, and desktop, to ensure it adapts seamlessly and eliminates the overflow issue.

Make necessary adjustments to the NAVBAR's HTML and CSS code, optimizing it for responsiveness without sacrificing functionality or aesthetics.

Tasks:

Identify the causes of responsiveness and overflow issues in the NAVBAR.
Implement responsive design techniques to make the NAVBAR 100% responsive.
Test the modified NAVBAR on multiple devices to ensure its adaptability and resolve the overflow problem.
Optimize the NAVBAR's HTML and CSS code for improved performance and maintainability.
Request for Assignment:
As a GGSOC '23 contributor, I would like to be assigned to this issue to enhance the responsiveness and resolve the overflow problem in the NAVBAR. I have experience in implementing responsive design and ensuring optimal user experience across various devices.

I am confident in my ability to address this issue promptly and effectively. By improving the NAVBAR's responsiveness, I will contribute to enhancing the overall usability and visual appeal of the website.

Please assign me this task, and I will commence working on it to provide an improved NAVBAR experience.

Thank you for considering my contribution!

**Comment by ankitjt** [comment] 2023-05-21 13:26
Please provide the page on which you found the issue, please share screenshots of the issue. 

A responsive navbar is implemented on blog page have a look into it , the same implementation will be done on all other pages.

**Comment by rishitachail** [comment] 2023-05-21 13:40
@ankitjt I have added the screenshot . Please have a look

**Comment by akshitagupta15june** [comment] 2023-05-22 16:39
some are working on the same

**Closed by akshitagupta15june** 2023-05-22 16:39 UTC
