### ISSUE TITLE
"Contributors" Section Design Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [akshitagupta15june/Moksh#563] opened 2023-05-28 19:06 UTC
## Description

**Is your feature request related to a problem? Please describe.**
No. It's enhancement in the existing design.

**Describe the solution you'd like**
Working on the design of this section, I can make it look even better.

**Describe alternatives you've considered**
Modification in the existing design

**Comment by karthiknadar1204** [comment] 2023-05-29 15:29
@iamRabia-N Please share what kind of changes do you wish to implement in the section

**Comment by iamRabia-N** [comment] 2023-05-29 15:49
@karthiknadar1204 

### Current Design
![moksh issue1 ss (1)](https://github.com/akshitagupta15june/Moksh/assets/115794049/bb32f3e1-571b-479e-a226-f519d1132644)

### Expected Updated Design
![moksh issue1 ss (2)](https://github.com/akshitagupta15june/Moksh/assets/115794049/04d62030-e26c-4ce5-8a20-123640d9cf4f)

**Comment by karthiknadar1204** [comment] 2023-05-29 15:51
We can definitely try it out,you can get started once the issue is assigned to you either by @Rakesh9100 or @akshitagupta15june

**Comment by Hritik1503** [comment] 2023-05-29 15:53
I am interested to work on this issue under GSSoC 2023 as a contributor

**Comment by Roar022** [comment] 2023-05-31 21:28
i would like to work on this issue, i will make its UI clean and eyecatching, i will cover 100% width, instead little amount of width that is being covered till now,  also i will fix the issue of overflowing image in mobile view, please assign it to me:)

**Closed** 2023-05-31 21:38 UTC
Labels: gssoc23
