### ISSUE TITLE
[BUG] In timer at Pomodoro Page

### ISSUE THREAD

**Issue by Sar-thak-3** [akshitagupta15june/Moksh#619] opened 2023-05-31 12:14 UTC
## Description

**Describe the bug:**
I think there is a bug in the timer on the Pomodoro page, after resetting the timer it starts from 5 min, not from 25 minutes. If it is not the bug, do close the issue

## Video

https://github.com/akshitagupta15june/Moksh/assets/100359818/4ca78e30-3c91-4094-ad2e-93ca209163b1

## Additional Information

**Device (please complete the following information):**
- OS: [e.g., Windows, macOS, Linux]
- Browser [e.g., Chrome, Safari, Firefox]
- Version [e.g., 22]

**Comment by Sar-thak-3** [comment] 2023-05-31 12:15
If this is the issue, kindly assign me under GSSoC 2023!

**Comment by ivanMehvish** [comment] 2023-06-01 17:58
I would like to work on this issue @akshitagupta15june under GSSoC'23

**Comment by ankit-kr27** [comment] 2023-06-03 03:32
I've recently worked on my own pomodoro web app, and would love to work on this too, you may assign this to me under GsSoc'23.

**Comment by ankitjt** [comment] 2023-06-05 10:03
@Sar-thak-3 wait for some time we are cross-checking whether the issue isn't a duplicate or assigned, if neither is the case we will assign to you.

**Comment by ankitjt** [comment] 2023-06-05 17:32
@Sar-thak-3 assigning the issue to you, pl adhere to time frame you have one week to submit your changes (Pull Request).

**Closed** 2023-06-08 07:27 UTC
Labels: Assigned
